import type { ReactNode } from "react";
import { AlertCircle, Inbox, RefreshCw } from "lucide-react";
import { AppFrame } from "./_shared/AppFrame";

function StatePanel({ title, icon, children, tone = "neutral" }: { title: string; icon: ReactNode; children: ReactNode; tone?: "neutral" | "danger" }) {
  return <section className="flex min-h-[260px] flex-1 flex-col overflow-hidden rounded-xl border border-[var(--ro-border)] bg-[var(--ro-surface)]"><div className="border-b border-[var(--ro-border)] bg-[var(--ro-bg)] px-5 py-4 text-base font-bold">{title}</div><div className={`flex flex-1 flex-col items-center justify-center gap-3 p-6 text-center ${tone === "danger" ? "text-[var(--ro-danger)]" : "text-[var(--ro-text-muted)]"}`}>{icon}<div className="text-base font-semibold">{children}</div></div></section>;
}
export function RentalsListStates() {
  return <AppFrame variant="desktop" active="rentals"><main className="min-h-full bg-[var(--ro-bg)] p-4 sm:p-6"><div className="mb-5 border-b border-[var(--ro-border)] pb-4"><h1 className="text-xl font-bold">حالات قائمة الإيجارات</h1><p className="mt-1 text-sm text-[var(--ro-text-muted)]">حالات واضحة عند تحميل البيانات أو تعذرها</p></div><div className="grid gap-4 md:grid-cols-1 lg:grid-cols-3"><StatePanel title="لا توجد نتائج" icon={<div className="flex h-12 w-12 items-center justify-center rounded-full bg-[var(--ro-neutral-bg)]"><Inbox className="h-6 w-6 text-[var(--ro-neutral)]" /></div>}>لا توجد إيجارات مطابقة للفلاتر<p className="mt-1 text-sm font-normal text-[var(--ro-text-faint)]">جرّب تغيير الحالة أو إزالة البحث</p></StatePanel><StatePanel title="جارٍ التحميل" icon={<div className="space-y-2"><div className="h-3 w-28 animate-pulse rounded bg-[var(--ro-border)]" /><div className="h-3 w-40 animate-pulse rounded bg-[var(--ro-border)]" /><div className="h-3 w-20 animate-pulse rounded bg-[var(--ro-border)]" /></div>}>جارٍ تحميل الإيجارات<p className="mt-1 text-sm font-normal text-[var(--ro-text-faint)]">يتم تجهيز أحدث بيانات العقود</p></StatePanel><StatePanel title="تعذر التحميل" tone="danger" icon={<div className="flex h-12 w-12 items-center justify-center rounded-full bg-[var(--ro-danger-bg)]"><AlertCircle className="h-6 w-6" /></div>}>تعذر تحميل الإيجارات<p className="mt-1 text-sm font-normal text-[var(--ro-text-muted)]">تحقق من الاتصال ثم حاول مرة أخرى</p><button className="mt-2 inline-flex h-10 items-center gap-2 rounded-lg border border-[var(--ro-danger-border)] bg-[var(--ro-surface)] px-4 text-sm font-bold text-[var(--ro-danger)]"><RefreshCw className="h-4 w-4" />إعادة المحاولة</button></StatePanel></div></main></AppFrame>;
}
