import { useMemo, useState } from "react";
import { Filter, Plus, Search } from "lucide-react";
import { AppFrame } from "./_shared/AppFrame";
import { PageHeader, PrimaryButton } from "./_shared/PageHeader";
import { MobileRentalCard, rentals } from "./_shared/rentalData";

export function RentalsListMobile() {
  const [query, setQuery] = useState(""); const [showFilter, setShowFilter] = useState(false); const [status, setStatus] = useState("all");
   const filtered = useMemo(() => rentals.filter((r) => (status === "all" || r.status === status) && `${r.customer} ${r.vehicle} ${r.id} ${r.phone} ${r.area}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [query, status]);
 return <AppFrame variant="mobile" active="rentals"><PageHeader title="الإيجارات" description="متابعة العقود والحجوزات" primaryAction={<PrimaryButton><Plus className="h-4 w-4" />إيجار جديد</PrimaryButton>} /><div className="flex gap-2 border-b border-[var(--ro-border)] bg-[var(--ro-surface)] p-3"><label className="relative flex-1"><span className="sr-only">البحث</span><Search className="pointer-events-none absolute inset-y-0 end-3 my-auto h-4 w-4 text-[var(--ro-text-faint)]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="بحث في الإيجارات" className="h-10 w-full rounded-lg border border-[var(--ro-border)] bg-[var(--ro-bg)] pe-9 ps-3 text-sm outline-none focus:border-[var(--ro-primary)]" /></label><button onClick={() => setShowFilter(!showFilter)} className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border ${showFilter ? "border-[var(--ro-primary)] bg-[var(--ro-primary-soft)] text-[var(--ro-primary)]" : "border-[var(--ro-border)] text-[var(--ro-text-muted)]"}`} aria-label="تصفية الإيجارات"><Filter className="h-4 w-4" /></button></div>{showFilter && <div className="border-b border-[var(--ro-border)] bg-[var(--ro-bg)] p-3"><label className="text-sm font-semibold text-[var(--ro-text-muted)]">تصفية حسب الحالة<select value={status} onChange={(e) => setStatus(e.target.value)} className="mt-2 h-10 w-full appearance-none rounded-lg border border-[var(--ro-border)] bg-[var(--ro-surface)] px-3 text-sm"><option value="all">كل الحالات</option><option value="active">نشط</option><option value="overdue">متأخر الإرجاع</option><option value="reserved">محجوز</option><option value="completed">مكتمل</option></select></label></div>}<div className="bg-[var(--ro-bg)]"><div className="flex items-center justify-between px-4 py-3 text-sm text-[var(--ro-text-muted)]"><b className="text-[var(--ro-text)]">الإيجارات الحالية</b><span>{filtered.length} إيجارات</span></div>{filtered.map((r) => <MobileRentalCard key={r.id} rental={r} />)}{filtered.length === 0 && <div className="p-12 text-center text-sm text-[var(--ro-text-muted)]">لا توجد نتائج</div>}</div></AppFrame>;
}
