import { useState } from "react";
import { ArrowRight, CalendarDays, CarFront, Check, CircleDollarSign, Clock3, FileDown, MapPin, MessageSquareText, MoreHorizontal, Plus, ReceiptText, UserRound, XCircle } from "lucide-react";
import { AppFrame } from "./_shared/AppFrame";
import { PageHeader, PrimaryButton, SecondaryButton } from "./_shared/PageHeader";
import { StatusBadge } from "./_shared/StatusBadge";
import { rentalStatus, paymentStatus, vehicleStatus } from "./_shared/statusConfig";
import { formatCurrency, formatDateCompact, formatDateTime, formatPlate } from "./_shared/format";
import { Ltr } from "./_shared/Ltr";

const money = (value: number) => formatCurrency(value);
function DetailSection({ title, icon: Icon, children, action }: { title: string; icon: typeof UserRound; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="border-b border-[var(--ro-border)] bg-[var(--ro-surface)] px-5 py-5 last:border-b-0"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-base font-bold text-[var(--ro-text)]"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-[var(--ro-primary-soft)] text-[var(--ro-primary)]"><Icon className="h-4 w-4" /></span>{title}</div>{action}</div>{children}</section>;
}
function InfoCell({ label, value, muted }: { label: string; value: import("react").ReactNode; muted?: boolean }) {
  return <div className="min-w-0"><div className="mb-1 text-xs font-medium text-[var(--ro-text-faint)]">{label}</div><div className={`truncate text-sm font-semibold ${muted ? "text-[var(--ro-text-muted)]" : "text-[var(--ro-text)]"}`}>{value}</div></div>;
}
const pickup = formatDateTime(18, 8, 2024, 9, 30);
const returned = formatDateTime(21, 8, 2024, 9, 30);

export function RentalDetailDesktop() {
  const [notice, setNotice] = useState(""); const [showPayment, setShowPayment] = useState(false);
  const runAction = (label: string) => setNotice(`${label} — تم تجهيز الإجراء للمراجعة`);
  const Button = ({ children, onClick, danger = false, primary = false }: { children: React.ReactNode; onClick: () => void; danger?: boolean; primary?: boolean }) => <button onClick={onClick} className={`flex h-11 w-full items-center justify-center gap-2 rounded-lg px-3 text-sm font-bold ${primary ? "bg-[var(--ro-primary)] text-white" : danger ? "border border-[var(--ro-danger-border)] text-[var(--ro-danger)]" : "border border-[var(--ro-border)] text-[var(--ro-text)]"}`}>{children}</button>;
  return <AppFrame variant="desktop" active="rentals">
    <PageHeader title="تفاصيل الإيجار" description="عقد رقم 240318" secondary={<SecondaryButton><ArrowRight className="h-4 w-4" /> العودة إلى الإيجارات</SecondaryButton>} primaryAction={<PrimaryButton><MoreHorizontal className="h-4 w-4" /> المزيد</PrimaryButton>} />
    <main className="p-6">{notice && <div className="mb-4 flex items-center gap-2 rounded-lg border border-[var(--ro-success-border)] bg-[var(--ro-success-bg)] px-4 py-3 text-sm font-semibold text-[var(--ro-success)]"><Check className="h-4 w-4" />{notice}</div>}
      <div className="grid items-start grid-cols-[minmax(0,1fr)_304px] gap-5"><div className="min-w-0 overflow-hidden rounded-xl border border-[var(--ro-border)] bg-[var(--ro-surface)]">
        <div className="flex items-start justify-between border-b border-[var(--ro-border)] px-5 py-5"><div><h2 className="text-xl font-bold">محمد بن عبدالله العتيبي</h2><p className="mt-1 text-sm text-[var(--ro-text-muted)]">Toyota Camry 2023 · {formatPlate("B", "482104")}</p></div><div className="flex items-center gap-3"><StatusBadge status={rentalStatus.active} /><button onClick={() => runAction("تم نسخ رقم العقد")} aria-label="نسخ رقم العقد" className="flex h-10 w-10 items-center justify-center rounded-lg border border-[var(--ro-border)] text-[var(--ro-text-muted)]"><ReceiptText className="h-4 w-4" /></button></div></div>
        <DetailSection title="بيانات العميل" icon={UserRound}><div className="grid grid-cols-3 gap-5"><InfoCell label="الاسم الكامل" value="محمد بن عبدالله العتيبي" /><InfoCell label="رقم الجوال" value={<Ltr>050 842 1963</Ltr>} /><InfoCell label="رقم الهوية" value={<Ltr>1024689317</Ltr>} muted /><InfoCell label="البريد الإلكتروني" value={<Ltr className="max-w-full truncate">m.alotaibi@example.sa</Ltr>} muted /><InfoCell label="نوع العميل" value="فردي" /><InfoCell label="الرخصة" value={<span>سارية حتى <Ltr>22-09-2025</Ltr></span>} /></div></DetailSection>
        <DetailSection title="المركبة" icon={CarFront} action={<StatusBadge status={vehicleStatus.rented} size="sm" />}><div className="grid grid-cols-4 gap-5"><InfoCell label="المركبة" value="Toyota Camry 2023" /><InfoCell label="رقم اللوحة" value={formatPlate("B", "482104")} /><InfoCell label="اللون" value="أبيض لؤلؤي" /><InfoCell label="عداد التسليم" value="42,860 km" /></div></DetailSection>
        <DetailSection title="فترة الإيجار ومواقع التسليم" icon={CalendarDays}><div className="grid grid-cols-2 gap-4">{[["الاستلام", pickup], ["الإرجاع", returned]].map(([label, value]) => <div key={label} className="rounded-lg border border-[var(--ro-border)] bg-[var(--ro-bg)] p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-[var(--ro-text-muted)]"><Clock3 className="h-4 w-4 text-[var(--ro-primary)]" />{label}</div><Ltr className="whitespace-nowrap text-sm font-bold">{value}</Ltr><div className="mt-2 text-sm text-[var(--ro-text-muted)]"><MapPin className="me-1 inline h-3.5 w-3.5" />فرع العليا، الرياض</div></div>)}</div></DetailSection>
        <DetailSection title="التسعير والمدفوعات" icon={CircleDollarSign} action={<StatusBadge status={paymentStatus.partial} size="sm" />}><div className="overflow-hidden rounded-lg border border-[var(--ro-border)]"><div className="grid grid-cols-3 bg-[var(--ro-bg)] px-4 py-3 text-xs font-semibold text-[var(--ro-text-muted)]"><span>البند</span><span>الكمية</span><span className="text-end">المبلغ</span></div>{[["أجرة الإيجار اليومية", "3 أيام × 185 USD", money(555)], ["التأمين القابل للاسترداد", "مبلغ ثابت", money(300)], ["الإجمالي المستحق", "—", money(855)]].map(([a,b,c], i) => <div key={a} className={`grid grid-cols-3 px-4 py-3 text-sm ${i ? "border-t border-[var(--ro-border)]" : ""} ${i === 2 ? "bg-[var(--ro-primary-soft)] font-bold" : ""}`}><span>{a}</span><span>{b}</span><strong className="text-end whitespace-nowrap">{c}</strong></div>)}</div><div className="mt-4 grid grid-cols-3 gap-4"><InfoCell label="الإجمالي" value={money(855)} /><InfoCell label="المدفوع" value={money(500)} /><div className="rounded-lg bg-[var(--ro-danger-bg)] px-4 py-2"><div className="text-xs font-medium text-[var(--ro-danger)]/80">المتبقي</div><div className="text-base font-bold text-[var(--ro-danger)]">{money(355)}</div></div></div></DetailSection>
        <DetailSection title="سجل الدفعات" icon={ReceiptText}><div className="space-y-3 text-sm"><div className="flex justify-between border-b border-[var(--ro-border)] pb-3"><span><Ltr>18-08-2024 — 9:45 AM</Ltr> · نقدًا</span><strong>{money(300)}</strong></div><div className="flex justify-between"><span><Ltr>18-08-2024 — 10:10 AM</Ltr> · تحويل بنكي</span><strong>{money(200)}</strong></div></div></DetailSection>
        <DetailSection title="سجل النشاط" icon={MessageSquareText} action={<SecondaryButton><Plus className="h-4 w-4" /> إضافة ملاحظة</SecondaryButton>}><div className="space-y-4 text-sm"><div><Ltr className="text-xs text-[var(--ro-text-faint)]">18-08-2024 — 9:30 AM</Ltr><b className="mt-1 block">تم إنشاء العقد</b><span className="text-[var(--ro-text-muted)]">بواسطة هبة العتيبي</span></div><div><Ltr className="text-xs text-[var(--ro-text-faint)]">18-08-2024 — 10 AM</Ltr><b className="mt-1 block">تم تسليم المركبة</b></div></div></DetailSection>
      </div>
      <aside className="sticky top-6 overflow-hidden rounded-xl border border-[var(--ro-border)] bg-[var(--ro-surface)]"><div className="bg-[var(--ro-primary-dark)] px-5 py-5 text-white"><div className="text-sm text-white/70">ملخص الإيجار</div><div className="mt-2"><StatusBadge status={rentalStatus.active} /></div></div><div className="space-y-5 px-5 py-5"><div className="flex justify-between text-sm"><span className="text-[var(--ro-text-muted)]">تاريخ الإرجاع</span><strong className="whitespace-nowrap">{formatDateCompact(21, 8, 2024)}</strong></div><div className="flex justify-between text-sm"><span className="text-[var(--ro-text-muted)]">مدة الإيجار</span><strong>3 أيام</strong></div><div className="flex justify-between border-b border-[var(--ro-border)] pb-5 text-sm"><span className="text-[var(--ro-text-muted)]">الإجمالي</span><strong>{money(855)}</strong></div><div className="grid gap-2"><Button primary onClick={() => setShowPayment(!showPayment)}><CircleDollarSign className="h-4 w-4" />تسجيل دفعة</Button>{showPayment && <div className="rounded-lg border border-[var(--ro-primary)] bg-[var(--ro-primary-soft)] p-3"><div className="mb-2 text-sm font-bold">تسجيل دفعة يدوية</div><div className="grid grid-cols-2 gap-2"><input aria-label="مبلغ الدفعة" placeholder="المبلغ USD" className="h-10 rounded border border-[var(--ro-border)] bg-[var(--ro-surface)] px-2 text-sm" /><select aria-label="طريقة الدفع" className="h-10 rounded border border-[var(--ro-border)] bg-[var(--ro-surface)] px-2 text-sm"><option>نقدًا</option><option>تحويل بنكي</option><option>بطاقة</option></select></div><button onClick={() => { setShowPayment(false); runAction("تم تسجيل الدفعة"); }} className="mt-2 h-9 w-full rounded bg-[var(--ro-primary)] text-sm font-bold text-white">حفظ الدفعة</button></div>}<Button onClick={() => runAction("تمديد الإيجار")}><CalendarDays className="h-4 w-4" />تمديد الإيجار</Button><Button onClick={() => runAction("إرجاع المركبة")}><CarFront className="h-4 w-4" />إرجاع المركبة</Button><Button danger onClick={() => runAction("إلغاء العقد")}><XCircle className="h-4 w-4" />إلغاء العقد</Button><Button onClick={() => runAction("طباعة وتصدير العقد")}><FileDown className="h-4 w-4" />طباعة / تصدير العقد</Button></div></div></aside></div>
    </main>
  </AppFrame>;
}