import { useState } from "react";
import { useLocation, useSearchParams } from "wouter";
import { confirmPasswordReset, requestPasswordReset } from "@workspace/api-client-react";
import { FormField, inputClass } from "@/components/ui/FormField";
import { getApiErrorMessage } from "@/lib/api-error";
import { InlineFeedback } from "@/components/ui/FeedbackState";

export default function PasswordResetPage() {
  const [, setLocation] = useLocation(); const [params] = useSearchParams();
  const token = params.get("token"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (saving) return; setSaving(true); setError(null); try { if (token) { await confirmPasswordReset({ token, password }); setMessage("تم تحديث كلمة المرور. يمكنك تسجيل الدخول الآن."); } else { await requestPasswordReset({ email }); setMessage("إذا كان البريد مسجلاً، ستصلك تعليمات إعادة التعيين."); } } catch (cause) { setError(getApiErrorMessage(cause).title); } finally { setSaving(false); } }
  const confirmation = Boolean(token);
  return <main className="min-h-dvh bg-background px-4 py-8"><form onSubmit={submit} className="mx-auto w-full max-w-sm space-y-4 rounded-2xl border border-card-border bg-card p-5 shadow-sm"><div><img src="/brand/logos/markab-logo-ar.png" alt="مَركب" className="markab-auth-logo-light mb-4 h-auto w-32" /><img src="/brand/logos/markab-logo-monochrome-light.png" alt="مَركب Markab" className="markab-auth-logo-dark mb-4 h-auto w-28 object-contain" /><h1 className="text-2xl font-bold">{confirmation ? "تعيين كلمة مرور جديدة" : "إعادة تعيين كلمة المرور"}</h1><p className="mt-1 text-sm text-muted-foreground">{confirmation ? "اختر كلمة مرور جديدة لحسابك." : "أدخل بريدك لطلب تعليمات إعادة التعيين."}</p></div>{message && <InlineFeedback variant="success">{message}</InlineFeedback>}{error && <InlineFeedback variant="error">{error}</InlineFeedback>}{confirmation ? <FormField label="كلمة المرور الجديدة" htmlFor="reset-password"><input id="reset-password" required minLength={8} type="password" dir="ltr" className={inputClass} value={password} onChange={(e) => setPassword(e.target.value)} /></FormField> : <FormField label="البريد الإلكتروني" htmlFor="reset-email"><input id="reset-email" required type="email" dir="ltr" className={inputClass} value={email} onChange={(e) => setEmail(e.target.value)} /></FormField>}<button className="w-full rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-60" disabled={saving || (confirmation ? password.length < 8 : !email)}>{saving ? "جارٍ الإرسال" : confirmation ? "تحديث كلمة المرور" : "إرسال الطلب"}</button><button type="button" className="w-full text-sm text-primary" onClick={() => setLocation("/login")}>العودة لتسجيل الدخول</button></form></main>;
}
