// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rental-ops/AnalyticsDesktop.tsx": () => import("../components/mockups/rental-ops/AnalyticsDesktop.tsx"),
  "./components/mockups/rental-ops/AppShellDesktop.tsx": () => import("../components/mockups/rental-ops/AppShellDesktop.tsx"),
  "./components/mockups/rental-ops/AppShellMobile.tsx": () => import("../components/mockups/rental-ops/AppShellMobile.tsx"),
  "./components/mockups/rental-ops/AppShellTablet.tsx": () => import("../components/mockups/rental-ops/AppShellTablet.tsx"),
  "./components/mockups/rental-ops/CreateRentalFormDesktop.tsx": () => import("../components/mockups/rental-ops/CreateRentalFormDesktop.tsx"),
  "./components/mockups/rental-ops/CreateRentalFormMobile.tsx": () => import("../components/mockups/rental-ops/CreateRentalFormMobile.tsx"),
  "./components/mockups/rental-ops/DashboardDesktop.tsx": () => import("../components/mockups/rental-ops/DashboardDesktop.tsx"),
  "./components/mockups/rental-ops/DashboardMobile.tsx": () => import("../components/mockups/rental-ops/DashboardMobile.tsx"),
  "./components/mockups/rental-ops/MobileMoreDrawer.tsx": () => import("../components/mockups/rental-ops/MobileMoreDrawer.tsx"),
  "./components/mockups/rental-ops/RentalDetailDesktop.tsx": () => import("../components/mockups/rental-ops/RentalDetailDesktop.tsx"),
  "./components/mockups/rental-ops/RentalDetailMobile.tsx": () => import("../components/mockups/rental-ops/RentalDetailMobile.tsx"),
  "./components/mockups/rental-ops/RentalDetailTablet.tsx": () => import("../components/mockups/rental-ops/RentalDetailTablet.tsx"),
  "./components/mockups/rental-ops/RentalsListDesktop.tsx": () => import("../components/mockups/rental-ops/RentalsListDesktop.tsx"),
  "./components/mockups/rental-ops/RentalsListMobile.tsx": () => import("../components/mockups/rental-ops/RentalsListMobile.tsx"),
  "./components/mockups/rental-ops/RentalsListStates.tsx": () => import("../components/mockups/rental-ops/RentalsListStates.tsx"),
  "./components/mockups/rental-ops/RentalsListTablet.tsx": () => import("../components/mockups/rental-ops/RentalsListTablet.tsx"),
  "./components/mockups/rental-ops/ReportsDesktop.tsx": () => import("../components/mockups/rental-ops/ReportsDesktop.tsx")
};
